---
name: CI — dt-eval-cli

on:
  pull_request:
    paths:
      - "dt-eval-cli/**"
      - ".github/workflows/ci-cli.yml"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04
    name: Test & Build
    defaults:
      run:
        shell: bash
        working-directory: dt-eval-cli
    env:
      FOLDER: dt-eval-cli
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: "${{ env.FOLDER }}/.nvmrc"
          registry-url: https://registry.npmjs.org
          cache: "npm"
          cache-dependency-path: "${{ env.FOLDER }}/package-lock.json"

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
